version: 2.1
orbs: { cypress: cypress-io/cypress@1 }
jobs:
  # seed retreat guru with fixture data
  test-ui:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      # get the new version
      - checkout

      # copy dependencies from cache if available
      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock"}}

      # install packages with yarn
      - run: yarn install

      # save dependencies to cache
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock"}}
          paths:
            - node_modules

      - run:
          name: build nextjs server
          command: yarn build

      - run:
          name: start nextjs server
          command: yarn start
          background: true

      # test
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  node-tests:
    jobs:
      - test-ui
